# Generated by Django 5.0.4 on 2024-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_classroom_unique_classroom'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name', 'short_name'), name='unique_school'),
        ),
    ]
