# Generated by Django 5.0.4 on 2024-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_school_unique_school'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='school',
            name='unique_school',
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_school'),
        ),
    ]
