from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views.v1.classroom import ClassrooomViewSet, TeacherViewSet, StudentViewSet, SchoolViewSet


router = DefaultRouter() #automatically generate URL patterns for your viewsets
router.register(r'classrooms', ClassrooomViewSet)
router.register(r'teachers', TeacherViewSet)
router.register(r'students', StudentViewSet)
router.register(r'schools', SchoolViewSet)

api_v1_urls = (router.urls, 'v1') #router.urls returns the list of URL patterns generated by the router. The second element of the tuple is the namespace of the URL patterns.

urlpatterns = [
    path('v1/', include(api_v1_urls))
]
